#微服务建议一定要写服务端口号和微服务名称
server:
  #端口号
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com
  client:
    service-url:
      #设置与eurekaServer交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/
