server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 120.92.164.250:8848 #nacos

management:
  endpoints:
    web:
      exposure:
        include: '*'
