server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名称进行路由(默认false)
      routes:
        - id: payment_route #路由的id,没有规定规则但要求唯一,建议配合服务名
          #          uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-provider-hystrix-payment
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_route2
          #          uri: http://localhost:8001
          uri: lb://cloud-provider-hystrix-payment
          predicates:
            - Path=/payment/lb/** #断言,路径相匹配的进行路由
            #指定时间后才能访问（After）时间往后写一小时
            - After=2020-06-17T12:53:40.325+08:00[Asia/Shanghai]


eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
